-- Generated by tests/nvim-langmap.sh from XKB us(colemak_dh_ortho),ru: in Normal
-- mode a Russian letter acts as the Colemak-DH key at the same spot.
return '№#,йq,ЙQ,цw,ЦW,уf,УF,кp,КP,еb,ЕB,нj,НJ,гl,ГL,шu,ШU,щy,ЩY,з\\;,З:,х[,Х{,ъ],Ъ},фa,ФA,ыr,ЫR,вs,ВS,аt,АT,пg,ПG,рm,РM,оn,ОN,лe,ЛE,дi,ДI,жo,ЖO,э\',Э\\",ё`,Ё~,яz,ЯZ,чx,ЧX,сc,СC,мd,МD,иv,ИV,тk,ТK,ьh,ЬH,б\\,,Б<,ю.,Ю>'
