#!/bin/sh
# nvim's Russian langmap (home/dot_config/nvim/lua/core/langmap.lua), generated from
# the XKB layouts: in Normal mode a Russian letter acts as the Colemak-DH key at the
# same spot (the key that types `d` types `м` in the Russian layout, so `мм` = `dd`).
# Run: sh tests/nvim-langmap.sh           checks the committed table (offline)
#      sh tests/nvim-langmap.sh --write   regenerates it, e.g. after a layout change
# Needs xkbcli (libxkbcommon), /usr/include/X11/keysymdef.h (xorgproto) and nvim.

set -u
here=$(cd "$(dirname "$0")" && pwd)
table=$here/../home/dot_config/nvim/lua/core/langmap.lua
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fails=0
check() { # check NAME CONDITION...
    name=$1; shift
    if "$@"; then echo "ok   $name"; else echo "FAIL $name"; fails=$((fails + 1)); fi
}

xkbcli compile-keymap --rules evdev --model pc105 --layout us,ru \
    --variant colemak_dh_ortho, >"$tmp/keymap" || exit 1

# Each key's first two levels in both groups; keysym names to characters through
# keysymdef.h's "U+XXXX" comments. Only non-ASCII characters are mapped: an ASCII one
# (the Russian `.` or `"`) is a different key in the English layout.
python3 - "$tmp/keymap" >"$tmp/langmap.lua" <<'EOF'
import re, sys
chars = {}
for line in open('/usr/include/X11/keysymdef.h'):
    m = re.match(r'#define XK_(\w+)\s+0x[0-9a-f]+\s*/\*[ (]*U\+([0-9A-F]+)', line)
    if m:
        chars.setdefault(m[1], chr(int(m[2], 16)))
keymap = open(sys.argv[1]).read()
pairs = []
for en, ru in re.findall(r'symbols\[1\]=\s*\[([^\]]*)\],\s*symbols\[2\]=\s*\[([^\]]*)\]', keymap):
    for e, r in zip(en.split(',')[:2], ru.split(',')[:2]):
        e, r = chars.get(e.strip()), chars.get(r.strip())
        if e and r and not r.isascii() and e.isascii() and e.isprintable():
            pairs.append(r + ('\\' + e if e in ',;\\"|' else e))
print('-- Generated by tests/nvim-langmap.sh from XKB us(colemak_dh_ortho),ru: in Normal')
print('-- mode a Russian letter acts as the Colemak-DH key at the same spot.')
print("return '" + ','.join(pairs).replace('\\', '\\\\').replace("'", "\\'") + "'")
EOF

if [ "${1:-}" = --write ]; then
    cp "$tmp/langmap.lua" "$table" && echo "wrote $table"
    exit
fi

check "the table matches the XKB layouts" cmp -s "$tmp/langmap.lua" "$table"

# nvim with only the langmap: Russian keys run the Colemak-DH commands
cat >"$tmp/test.lua" <<EOF
vim.o.langmap = dofile('$table')
local function run(keys, lines)
  vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  vim.api.nvim_feedkeys(keys, 'xt', false)
  return table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), '|')
end
local out = {
  'mm=' .. run('мм', { 'one', 'two' }), -- dd
  'x=' .. run('ч', { 'abc' }), -- x
  'Ax=' .. run('Фч\27', { 'abc' }), -- A, then x is typed text
  'count=' .. select(2, vim.o.langmap:gsub('[\194-\244][\128-\191]*', '')), -- non-ASCII
}
vim.fn.writefile(out, '$tmp/out')
vim.cmd 'qa!'
EOF
nvim --clean --headless -c "luafile $tmp/test.lua" >/dev/null 2>&1
out=$(cat "$tmp/out" 2>/dev/null)
has() { printf '%s\n' "$out" | grep -qx "$1"; }
check "мм deletes a line (dd)" has 'mm=two'
check "ч deletes a character (x)" has 'x=bc'
check "Ф appends (A); Insert mode types Russian" has 'Ax=abcч'
check "all 33 letters in both cases, and №" has 'count=67'

if [ $fails -gt 0 ]; then
    echo "$fails failed"
    exit 1
fi
echo "all passed"
