#!/bin/sh
# Lock the screen: i3lock-color with the screen blurred, a clock and the keyboard
# layout, in Ayu's orange. Plain i3lock (apt's) has none of these options: it gets a
# dark screen instead. Extra arguments go to i3lock (xss-lock passes --nofork).

if ! i3lock --version 2>&1 | grep -q 'Raymond Li'; then
    exec i3lock --color=0f1419 "$@"
fi

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#FA8D3FE6'
TEXT='#FA8D3FE6'
WRONG='#FF7383bb'
VERIFYING='#399EE6E6'

exec i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"    \
--keylayout 1                \
"$@"
